# Generated by Django 4.2 on 2024-05-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0029_array_max_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='default_program_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='default program start time'),
        ),
    ]
