name: CI pipeline
on: [push, pull_request] #Which triggers there are available?
jobs:
  test-job:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ "3.10" ]

    container: python:${{ matrix.python-version }}-bullseye

    services:
      # Label used to access the service container
      redis:
        image: redis
        ports:
          - 6379:6379

      db:
        # Docker Hub image
        image: postgres:15
        # Provide the password for postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - run: echo "Starting Tests"
      - run: apt update && apt install -y gcc libpq-dev libz-dev
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Poetry
        run: |
            curl -fsS -o get-poetry.py https://install.python-poetry.org
            python get-poetry.py -y
            echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Run tests
        run: poetry run python manage.py test -v 3 --settings=serafin.settings_tests